version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest-18
    restart: always
    environment:
      - TZ=Asia/Saigon
    ports:
      - "1880:1880"
    network_mode: host
    volumes:
      - ~/node-red/data:/data

networks:
  node-red-net: